### ISSUE TITLE
Jenkins jobs do not build on commits in scmm

### ISSUE THREAD

**Issue by phaenr** [cloudogu/k8s-gitops-playground#16]
### Behaviour: 

Jenkins jobs within a multipipeline not having any build-triggers in place. A commit onto the corresponding repository in scmm does not trigger a build. 

### Wanted Behaviour:

Jenkins jobs poll the scmm and start building upon commits to repositories on scmm. 

### Steps to reproduce:

- make changes to e.g. fluxv1/petclinic-plain 
- commit changes to scmm
- watch jenkins (does not build, have to start it manually)

**Comment by schnatterer** [comment]
I think I broke it, when [I changed the ports](https://github.com/cloudogu/k8s-gitops-playground/blame/288c6c70657223930adf728d1ac1a2ccc0371d7c/jenkins/values.yaml#L12)

Some background on how the build trigger works:

SCMM calls a webhook (via its Jenkins Plugin) on the Jenkins instance. To do so, SCMM needs to know Jenkins'  root URL.
We configure this URL [here](https://github.com/cloudogu/k8s-gitops-playground/blob/288c6c70657223930adf728d1ac1a2ccc0371d7c/scm-manager/initscmm.sh#L109)  as `http://jenkins:8080`.
This uses the service name and internal port of the service (note that there might be a difference to the node port, see [here](https://github.com/cloudogu/k8s-diagrams/tree/6b3661758594a470e271d2656063d5576f2d4706#services-nodes-and-pods-explained-including-ip-addresses) for details.

One reason for the builds not to start automatically is that the webhook is not delivered. Without having looked into it in more detail, I presume changing `http://jenkins:8080` to `http://jenkins` resolves this.
