### ISSUE TITLE
missing user for jenkins ui since upgrade to newest jenkins helm chart version

### ISSUE THREAD

**Issue by marekzan** [cloudogu/k8s-gitops-playground#20]
**Behaviour:**
When opening the jenkins ui for the first time after a fresh deployment, you will be prompted to create an admin user.

**Wanted Behaviour**:
The user should have been created via config from code

**Steps to reproduce**:
Deploy a fresh Playground.
Wait until Jenkins is up and running.
Open Jenkins UI
You will be prompted to create ad admin user

**Comment by schnatterer** [comment]
Seems to be fixed via #31
